<PlaylistCard>:
    size_hint_y: None
    height: "50dp"
    style: "elevated"
    on_release: root.on_release_callback(root.playlist_id)

    MDBoxLayout:
        orientation: 'horizontal'
        size_hint_y: None
        height: "40dp"
        padding: "5dp"

        FitImage:
            source: root.thumbnail_url
            size_hint_x: None
            width: "40dp"

        MDLabel:
            text: root.title
            size_hint_y: None
            height: "40dp"