"""youtube_id unique index

Revision ID: a000375676d3
Revises: 7a6dc4cbd397
Create Date: 2025-03-15 12:39:55.806866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a000375676d3'
down_revision: Union[str, None] = '7a6dc4cbd397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tracks_youtube_id', 'tracks', ['youtube_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tracks_youtube_id', table_name='tracks')
    # ### end Alembic commands ###
