#:include src/screens/tags/create_dialog/layout.kv
#:include src/screens/tags/tag_card/layout.kv

<TagsScreen>:
    MDBoxLayout:
        orientation: 'vertical'
        padding: 10
        spacing: 10

        MDBoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: 50

            MDIconButton:
                icon: "plus"
                on_release: root.create_dialog.open()

        MDScrollView:
            MDList:
                id: tag_list